### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by LAnp03** [unseim/WYIDCardOCR#11]
Undefined symbols for architecture arm64:
  "_ZIM_SaveImage", referenced from:
      ImgSave(tagIMG, char const*) in libbankcard.a(gjimage.o)
  "_ZIM_LoadImage", referenced from:
      ImgLoad(tagIMG&, char const*) in libbankcard.a(gjimage.o)
  "_ZIM_DoneImage", referenced from:
      ImgLoad(tagIMG&, char const*) in libbankcard.a(gjimage.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by LAnp03** [comment]
在startRunning的时候会造成内存泄漏

**Comment by Heiyuan** [comment]
这个问题怎么处理的?
